server:
  port: 8010
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: swagger
          uri: http://localhost:8010/api/swagger-ui.html
          predicates:
            - Path=/api/swagger

        - id: users
          uri: http://localhost:8011/api/users/
          predicates:
            - Path=/api/users/**

        - id: friends
          uri: http://localhost:8012/
          predicates:
            - Path=/api/friends/**

        - id: chat
          uri: http://localhost:8013/
          predicates:
            - Path=/api/chat/**

        - id: notifications
          uri: http://localhost:8014/
          predicates:
            - Path=/api/notif/**