version: "3.9"

services:
  db_users:
    image: postgres:14.1-alpine
    container_name: db_users_jessenger
    ports:
      - "6666:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "passwd"
      POSTGRES_DB: "users"
    volumes:
      - "./postgres_data:/var/lib/postgresql"