version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    container_name: jessenger_db
    ports:
      - "6666:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "postgres"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
      - "./init-scripts:/docker-entrypoint-initdb.d"