###
GET http://localhost:7070/hello

###
GET http://localhost:7070/profile/login


###
POST http://localhost:7070/register
Content-Type: application/json

{
  "login": "login",
  "firstName": "firstName",
  "middleName": "middleName",
  "lastName": "lastName",
  "birthDate": "2003-03-16"
}
