###
GET http://localhost:7070/hello

###
GET http://localhost:7070/profile/login


###
POST http://localhost:7070/api/users/register
Content-Type: application/json

{
  "login": "login",
  "firstMiddleLastName": "firstName",
  "password": "pass"
}