spring.config.import: classpath:/security-config.yml
# Эти три тире обозначают, что это мы создаём отдельный YAML файл.
# Всё это нужно чтобы можно было перезаписывать конфигурацию, подтянутую из security-config.yml
# Подробнее https://stackoverflow.com/questions/65216091/override-property-with-my-profile-dev-in-spring-boot-2-4
---
spring.config.import: classpath:/eureka-config.yml
---

server:
  port: 8011

app:

  test-message:
    current-service: "UserService"

spring:

  application:
    name: user-service

  devtools:
    restart:
      enabled: true

  flyway:
    enabled: false
    locations: classpath:migrations
    url: "jdbc:postgresql://localhost:6666/user_db"
    user: "user_user"
    password: "user_password"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:6666/user_db"
    username: "user_user"
    password: "user_password"

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true # Делаем так, чтобы Spring сам управлял сущностями БД
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  mvc: # Чтобы работали HTTP методы PUT, PATCH, DELETE
    hiddenmethod:
      filter:
        enabled: true

