spring.config.import: classpath:/security-config.yml
# Эти три тире обозначают, что это мы создаём отдельный YAML файл.
# Всё это нужно чтобы можно было перезаписывать конфигурацию, подтянутую из security-config.yml
# Подробнее https://stackoverflow.com/questions/65216091/override-property-with-my-profile-dev-in-spring-boot-2-4
---
spring.config.import: classpath:/eureka-config.yml
---


minio:
  access-key: ${S3_ACCESS_KEY:Wu117C4zjyObyN1nffsT}
  secret-key: ${S3_SECRET_KEY:EBNP9hZkijsngD5HBhAu78sUFYqXXAIHZDE2E2cd}
  bucket-name: ${S3_BUCKET:jessenger-bucket}
  url: http://${S3_HOST:minio}:${S3_PORT:8080}

server:
  port: ${APP_PORT:8080}


spring:
  servlet:
    multipart:
      max-file-size: 10MB

  application:
    name: fileserver-service

  devtools:
    restart:
      enabled: true

  flyway:
    enabled: false
    locations: classpath:migrations
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DB}"
    user: "${DB_USER}"
    password: "${DB_PASSWORD}"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DB}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true # Делаем так, чтобы Spring сам управлял сущностями БД
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
