server:
  port: 8014

app:
  test-message:
    current-service: "NotificationsService"

spring:
  devtools:
    restart:
      enabled: true
  flyway:
    locations: classpath:migrations
    url: "jdbc:postgresql://localhost:6666/notifications_db"
    user: "notifications_user"
    password: "notifications_password"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:6666/notifications_db"
    username: "notifications_user"
    password: "notifications_password"

  jpa:
    hibernate:
      ddl-auto: validate
    #    generate-ddl: true # Делаем так, чтобы Spring сам управлял сущностями БД
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true


  mvc: # Чтобы работали HTTP методы PUT, PATCH, DELETE
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: notifications-service