server:
  port: 8012
app:
  test-message:
    current-service: "FriendsService"

eureka:
  client:
    enabled: true
    service-url:
        defaultZone: http://localhost:8020/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: friends-service
  devtools:
    restart:
      enabled: true
  flyway:
    locations: classpath:migrations
    url: "jdbc:postgresql://localhost:6666/friends_db"
    user: "friends_user"
    password: "friends_password"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:6666/friends_db"
    username: "friends_user"
    password: "friends_password"

  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true # Делаем так, чтобы Spring сам управлял сущностями БД
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true


  mvc: # Чтобы работали HTTP методы PUT, PATCH, DELETE
    hiddenmethod:
      filter:
        enabled: true