spring.config.import: classpath:/security-config.yml
# Эти три тире обозначают, что это мы создаём отдельный YAML файл.
# Всё это нужно чтобы можно было перезаписывать конфигурацию, подтянутую из security-config.yml
# Подробнее https://stackoverflow.com/questions/65216091/override-property-with-my-profile-dev-in-spring-boot-2-4
---
spring.config.import: classpath:/eureka-config.yml
---

server:
  port: ${APP_PORT:8080}

app:
  test-message:
    current-service: "FriendsService"
  id: 1

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:8040}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin}
  cloud.stream.bindings:
    newNotificationEvent-out-0:
      destination: notifications-queue

  application:
    name: friends-service
  devtools:
    restart:
      enabled: true
  flyway:
    enabled: false
    locations: classpath:migrations
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DB}"
    user: "${DB_USER}"
    password: "${DB_PASSWORD}"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DB}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true # Делаем так, чтобы Spring сам управлял сущностями БД
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true


  mvc: # Чтобы работали HTTP методы PUT, PATCH, DELETE
    hiddenmethod:
      filter:
        enabled: true