server:
  port: 8020

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: localhost

app:
  test-message:
    current-service: eureka

spring:
  application:
    name: eureka
  devtools:
    restart:
      enabled: true
  flyway:
    locations: classpath:migrations
    url: "jdbc:postgresql://localhost:6666/eureka_db"
    user: "eureka_user"
    password: "eureka_password"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:6666/eureka_db"
    username: "eureka_user"
    password: "eureka_password"

  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true # Делаем так, чтобы Spring сам управлял сущностями БД
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true


  mvc: # Чтобы работали HTTP методы PUT, PATCH, DELETE
    hiddenmethod:
      filter:
        enabled: true