server:
  port: 8013
  servlet:
    context-path: "/chat"

app:
  test-message:
    current-service: "ChatService"


spring:
  devtools:
    restart:
      enabled: true
  flyway:
    locations: classpath:migrations
    url: "jdbc:postgresql://localhost:6666/chat_db"
    user: "chat_user"
    password: "chat_password"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:6666/chat_db"
    username: "chat_user"
    password: "chat_password"

  jpa:
    hibernate:
      ddl-auto: validate
    #    generate-ddl: true # Делаем так, чтобы Spring сам управлял сущностями БД
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true


  mvc: # Чтобы работали HTTP методы PUT, PATCH, DELETE
    hiddenmethod:
      filter:
        enabled: true