---
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka}:${EUREKA_PORT:8080}/eureka/
  instance:
    prefer-ip-address: true
---

server:
  port: ${APP_PORT:8080}

app:
  test-message:
    current-service: swagger-aggregator
  id: 13

springdoc:
  swagger-ui:
    configUrl: "/swagger-config.json"
spring:
  application:
    name: swagger-aggregator