---
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8020/eureka/
  instance:
    prefer-ip-address: true
---

server:
  port: 8021

app:
  test-message:
    current-service: swagger-aggregator
  id: 13

springdoc:
  swagger-ui:
    configUrl: "/swagger-config.json"
spring:
  application:
    name: swagger-aggregator